[workspace]
name = "sp1-tee"
members = ["host", "enclave", "common"]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
sp1-tee-enclave = { path = "./enclave" }
sp1-tee-host = { path = "./host" }
sp1-tee-common = { path = "./common" }

vsock = "0.5"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
thiserror = "1.0"
clap = { version = "4.5.30", features = ["derive"] }