[workspace]
name = "sp1-tee"
members = ["host", "enclave", "common"]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
sp1-tee-host = { path = "./host" }
sp1-tee-enclave = { path = "./enclave" }
