ARG ENCLAVE_VERSION

# ---- Build Stage ----
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS builder

ARG DEBUG_MODE=0
ARG ENCLAVE_VERSION

# Install system dependencies required to build Rust projects
RUN yum update -y \
    && yum install -y gcc clang git

# Install Rust via rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR app

COPY scripts/install-guest.sh ./

# Make sure your install-guest script is executable and run it
RUN sed -i 's/sudo //g' ./install-guest.sh
RUN chmod +x ./install-guest.sh
RUN ./install-guest.sh

# Copy the entire Rust workspace into /app
COPY . ./

# Sanity check that cmake is installed.
RUN cmake --version

RUN if [ "${DEBUG_MODE}" -eq "1" ]; then \
        cd enclave/v${ENCLAVE_VERSION}; \
        cargo build --release --bin sp1-tee-enclave --features debug-mode,enclave; \
    else \
        cd enclave/v${ENCLAVE_VERSION}; \
        # Use --locked to ensure the build is reproducible.
        cargo build --release --bin sp1-tee-enclave --locked --features enclave; \
    fi

# ---- Runtime Stage ----
FROM public.ecr.aws/amazonlinux/amazonlinux:2023

ARG ENCLAVE_VERSION

# Copy the binary from the build stage
COPY --from=builder /app/enclave/v$ENCLAVE_VERSION/target/release/sp1-tee-enclave /usr/local/bin/sp1-tee-enclave

# Allow 1 Billion total unconstrained cycles.
ENV UNCONSTRAINED_CYCLE_LIMIT=1000000000

# Set the entrypoint to the enclave binary.
ENTRYPOINT ["/usr/local/bin/sp1-tee-enclave", "--enc-key-arn", "none"]
