[package]
name = "sp1-tee-host"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sp1-tee-server"
path = "bin/server.rs"

[[bin]]
name = "vsock_test"
path = "bin/vsock_test.rs"

[[bin]]
name = "sp1-tee-setup"
description = "Deploys the contracts, validates the attestations and adds the signers to the contracts."
path = "bin/setup.rs"

[[bin]]
name = "save_attestation"
description = "Saves the attestation doc to S3, mostly used for testing."
path = "bin/save_attestation.rs"

[[bin]]
name = "validate_attestations"
description = "Builds the docker image locally, requires nitro-cli, validates the signer attestations against the S3 registry."
path = "bin/validate_attestations.rs"

[dependencies]
sp1-tee-common = { workspace = true }
tokio-vsock = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
k256 = { workspace = true }

alloy = { version = "0.11.1", features = ["full", "signer-ledger"] }

# Attestation Helpers
aws-nitro-enclaves-cose = { git = "https://github.com/nhtyy/aws-nitro-enclaves-cose.git", branch = "main" }
aws-nitro-enclaves-nsm-api = { workspace = true }
serde_json = "1.0.139"
aws-config = "1.5.17"
aws-sdk-s3 = "1.77.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[features]
production = []