[package]
name = "sp1-tee-host"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sp1-tee-server"
path = "bin/server.rs"

[[bin]]
name = "vsock_test"
path = "bin/vsock_test.rs"

[[bin]]
name = "sp1-tee-setup"
description = "Deploys the contracts, adds PCRs and registers the signer."
path = "bin/setup.rs"

[[bin]]
name = "get_attestation_doc"
description = "Gets the attestation doc from the enclave, and prints it as a JSON object."
path = "bin/get_attestation.rs"

[dependencies]
sp1-tee-common = { workspace = true }
tokio-vsock = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
alloy = { version = "0.11.1", features = ["full", "signer-ledger"] }

# Attestation Helpers
aws-nitro-enclaves-cose = { git = "https://github.com/nhtyy/aws-nitro-enclaves-cose.git", branch = "main" }
aws-nitro-enclaves-nsm-api = { workspace = true }
serde_json = "1.0.139"
