use std::time::{Duration, SystemTime, UNIX_EPOCH};

use alloy::hex::FromHexError;
use alloy::primitives::Address;
use attestation_doc_validation::error::{AttestError, AttestResult};
use aws_config::{BehaviorVersion, Region};
use aws_sdk_s3::operation::get_object::GetObjectError;
use aws_sdk_s3::operation::list_objects_v2::ListObjectsV2Error;
use aws_sdk_s3::primitives::ByteStreamError;
use aws_sdk_s3::{error::SdkError, operation::put_object::PutObjectError};
use serde::{Deserialize, Serialize};
use sp1_tee_common::CommunicationError;
#[cfg(feature = "server")]
use sp1_tee_common::{EnclaveRequest, EnclaveResponse};

use aws_nitro_enclaves_nsm_api::api::AttestationDoc;

#[cfg(feature = "server")]
use crate::ethereum_address_from_encoded_point;
#[cfg(feature = "server")]
use crate::HostStream;

// Attestations expire every 3 hours and we update every 30 mins.
pub const ATTESTATION_INTERVAL: Duration = Duration::from_secs(30 * 60);

/// On-disk schema version for [`SignersSnapshot`].
///
/// Bumped only when the wire format changes. Readers reject snapshots
/// whose `schema_version` does not match this constant — operators must
/// deploy matching writer/reader pairs before regenerating.
pub const SNAPSHOT_SCHEMA_VERSION: u32 = 1;

/// Upper bound on serialized snapshot size accepted by readers.
///
/// Production fleets carry a handful of signers (<10 today). The serialized
/// form is u64 LE outer length + a few small metadata fields + 20 bytes per
/// signer, so realistic snapshots are well under 1 KiB. The 1 MiB cap exists
/// solely to bound the memory a malicious or corrupted object can force.
pub const MAX_SNAPSHOT_BYTES: usize = 1 << 20;

/// Durable serving artifact for `/signers`.
///
/// Generated by `sp1-tee-snapshot-generate` after running fresh raw
/// attestations through the full Nitro CA + version + pubkey-derivation
/// pipeline. The wire format on the `/signers` response body remains
/// `bincode::serialize(&signers)` (i.e. just the inner [`Vec<Address>`]);
/// the wrapping struct exists so the on-disk artifact can carry metadata
/// for ops/debug and so the schema can evolve via [`SNAPSHOT_SCHEMA_VERSION`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignersSnapshot {
    /// On-disk schema version. See [`SNAPSHOT_SCHEMA_VERSION`].
    pub schema_version: u32,
    /// SP1 TEE protocol version the snapshot was generated for.
    pub sp1_tee_version: u32,
    /// Unix seconds at write time. Diagnostic only — readers do not enforce
    /// freshness here. Snapshot durability comes from refusing to overwrite
    /// with zero signers, not from a TTL.
    pub generated_at_unix: u64,
    /// Verified signer addresses. Writers refuse to publish a snapshot
    /// with this empty; readers reject if they observe it empty.
    pub signers: Vec<Address>,
    /// Number of raw attestations the generator processed. Diagnostic only.
    pub source_count: u64,
}

/// S3 key for the signers snapshot at a given SP1 TEE version.
pub fn snapshot_key(version: u32) -> String {
    format!("signers-v{version}.bin")
}

/// Creates an S3 client from the environment variables.
///
/// For EC2 instances, the environment variables are set automatically.
/// Used for both legacy raw-attestation writes and the durable snapshots
/// bucket (read+write); both buckets live in the same region and share
/// the same EC2 instance role.
///
/// # Panics
///
/// This function will panic if the environment variables are not set.
pub(crate) async fn s3_client_write() -> aws_sdk_s3::Client {
    // Loads from environment variables.
    let aws_config = aws_config::defaults(BehaviorVersion::latest())
        // buckets are in us-east-1
        .region(Region::new("us-east-1"))
        .load()
        .await;

    // Create the S3 client.
    aws_sdk_s3::Client::new(&aws_config)
}

/// Creates a client that doesnt sign requests
pub(crate) async fn s3_client_read_only() -> aws_sdk_s3::Client {
    // Loads from environment variables.
    let aws_config = aws_config::defaults(BehaviorVersion::latest())
        // buckets are in us-east-1
        .region(Region::new("us-east-1"))
        .no_credentials()
        .load()
        .await;

    // Create the S3 client.
    aws_sdk_s3::Client::new(&aws_config)
}

#[derive(Debug)]
pub struct SaveAttestationArgs {
    /// The CID of the enclave to connect to.
    pub cid: u32,

    /// The port of the enclave to connect to.
    pub port: u16,

    /// The S3 Bucket to write to
    pub bucket: String,
}

impl Default for SaveAttestationArgs {
    fn default() -> Self {
        Self {
            cid: 10,
            port: sp1_tee_common::ENCLAVE_PORT,
            bucket: crate::S3_BUCKET.to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum SaveAttestationError {
    #[error("Failed to put object: {0:?}")]
    S3PutObjectError(#[from] SdkError<PutObjectError>),

    #[error("Failed retrieve the attestation: {0:?}")]
    RetrieveAttestationError(#[from] RetrieveAttestationError),
}

#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum RetrieveAttestationError {
    #[error("Failed to communicate with enclave: {0:?}")]
    VsockError(#[from] CommunicationError),

    #[error("Got a bad public key from the enclave, this is a bug.")]
    BadPublicKey,

    #[error("Unexpected message from enclave, expected signing key attestation, got {0}")]
    UnexpectedMessage(&'static str),
}

/// Save the attestation to S3.
///
/// This function will connect to the enclave, request the signing key attestation, and save it to S3.
pub async fn save_attestation(
    raw_attestation: RawAttestation,
    bucket: String,
) -> Result<(), SaveAttestationError> {
    let s3_client = s3_client_write().await;

    tracing::info!(
        "Saving attestation to S3 for address: {}",
        raw_attestation.address
    );

    let key = raw_attestation.address.to_string();

    // Write the attestation to S3.
    s3_client
        .put_object()
        .bucket(bucket)
        .key(key)
        .body(raw_attestation.attestation.into())
        .send()
        .await?;

    Ok(())
}

#[derive(Debug, thiserror::Error)]
pub enum GetAttestationError {
    #[error("Failed to list attestations: {0}")]
    ListAttestationsError(#[from] SdkError<ListObjectsV2Error>),

    #[error("Failed to get object: {0}")]
    S3GetObjectError(#[from] SdkError<GetObjectError>),

    #[error("Failed to parse key as address: {0}")]
    ParseAddressError(#[from] FromHexError),

    #[error("Failed to recieve bytestream: {0}")]
    ByteStreamError(#[from] ByteStreamError),
}

pub struct RawAttestation {
    pub address: Address,
    pub attestation: Vec<u8>,
}

#[cfg(feature = "server")]
pub async fn retrieve_attestation_from_enclave(
    cid: u32,
    port: u16,
) -> Result<RawAttestation, RetrieveAttestationError> {
    // Connect to the enclave.
    let mut stream = HostStream::new(cid, port).await?;

    // Request the signing key attestation.
    let attest_signing_key = EnclaveRequest::AttestSigningKey;
    let get_public_key = EnclaveRequest::GetPublicKey;

    stream.send(attest_signing_key).await?;
    stream.send(get_public_key).await?;

    let attestation = match stream.recv().await? {
        EnclaveResponse::SigningKeyAttestation(attestation) => attestation,
        msg => {
            return Err(RetrieveAttestationError::UnexpectedMessage(msg.type_of()));
        }
    };

    let public_key = match stream.recv().await? {
        EnclaveResponse::PublicKey(public_key) => public_key,
        msg => {
            return Err(RetrieveAttestationError::UnexpectedMessage(msg.type_of()));
        }
    };

    // The address of the enclave is the S3 bucket key.
    let address = ethereum_address_from_encoded_point(&public_key)
        .ok_or(RetrieveAttestationError::BadPublicKey)?;

    Ok(RawAttestation {
        address,
        attestation,
    })
}

/// Tries to fetch all attestations from S3.
///
/// # Errors
/// - [`GetAttestationError::ListAttestationsError`] - Failed to list attestations.
/// - [`GetAttestationError::S3GetObjectError`] - Failed to get an object.
/// - [`GetAttestationError::ParseAddressError`] - Failed to parse an address.
/// - [`GetAttestationError::ByteStreamError`] - Failed to collect the byte stream.
///
/// # Panics
///
/// See [`s3_client`] for more details.
pub async fn get_raw_attestations() -> Result<Vec<RawAttestation>, GetAttestationError> {
    let s3_client = s3_client_read_only().await;

    let attestation_s3_objs = s3_client
        .list_objects_v2()
        .bucket(crate::S3_BUCKET.to_string())
        .send()
        .await?;

    let mut attestations = Vec::new();

    let contents = attestation_s3_objs.contents.unwrap_or_default();
    if contents.is_empty() {
        tracing::warn!(
            "S3 bucket {} returned no attestation objects; serving empty signer list",
            crate::S3_BUCKET
        );
        return Ok(attestations);
    }

    for metadata in &contents {
        let Some(key) = metadata.key.clone() else {
            tracing::warn!(
                "S3 object in {} missing key field; skipping",
                crate::S3_BUCKET
            );
            continue;
        };

        let key_as_address = match key.parse::<Address>() {
            Ok(addr) => addr,
            Err(e) => {
                tracing::warn!("S3 object key {key} not a valid address: {e}; skipping");
                continue;
            }
        };

        // Fetch the actual object from S3.
        let object = s3_client
            .get_object()
            .bucket(crate::S3_BUCKET.to_string())
            .key(key)
            .send()
            .await?;

        let bytes = object.body.collect().await?.to_vec();

        attestations.push(RawAttestation {
            address: key_as_address,
            attestation: bytes,
        });
    }

    Ok(attestations)
}

#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum AttestationVerificationError {
    #[error("Failed to verify attestation: {0}")]
    VerificationError(#[from] AttestError),

    #[error("Failed to verify PCR0 expected: {0} actual: {1}")]
    Pcr0VerificationError(String, String),

    #[error("Failed to get attestations: {0}")]
    GetAttestationError(#[from] GetAttestationError),

    #[error("Missing or invalid pubkey field on attestation docment")]
    MissingRequiredField(&'static str),

    #[error(
        "Invalid associated attestation for signer, expected: {0} found: {1} \n this is a bug."
    )]
    AddressMismatch(Address, Address),

    #[error("Version mismatch, expected: {0} found: {1}")]
    VersionMismatch(String, String),
}

/// Verifies an attestation for a given signer and hex-encoded PCR0 value.
///
/// # Errors
/// - [`AttestationVerificationError::GetAttestationError`] - Failed to get the attestation.
/// - [`AttestationVerificationError::Pcr0VerificationError`] - Failed to verify the PCR0 value.
/// - [`AttestationVerificationError::VerificationError`] - Failed to verify the attestation.
pub async fn verify_attestation_for_signer(
    signer: Address,
    version: u32,
    pcr0: &str,
) -> Result<(), AttestationVerificationError> {
    let client = s3_client_read_only().await;

    // Fetch the attestation from S3.
    let attestation = client
        .get_object()
        .bucket(crate::S3_BUCKET.to_string())
        .key(signer.to_string())
        .send()
        .await
        .map_err(GetAttestationError::from)?;

    let bytes = attestation
        .body
        .collect()
        .await
        .map_err(GetAttestationError::from)?
        .to_vec();

    // Verify the attestations root of trust.
    let doc = verify_attestation(bytes.as_ref())?;

    // Verify the PCR0 value.
    let doc_pcr0 = hex::encode(doc.pcrs[&0].as_ref());
    if doc_pcr0 != pcr0.replace("0x", "") {
        return Err(AttestationVerificationError::Pcr0VerificationError(
            pcr0.to_string(),
            doc_pcr0,
        ));
    }

    // Verify the version of the attestation.
    if doc
        .user_data
        .as_ref()
        .ok_or(AttestationVerificationError::MissingRequiredField(
            "user_data",
        ))?
        != &version.to_le_bytes()
    {
        return Err(AttestationVerificationError::VersionMismatch(
            version.to_string(),
            String::from_utf8(doc.user_data.as_ref().unwrap().to_vec()).unwrap(),
        ));
    }

    // Verify the address of the attestation.
    let derived_address = doc
        .public_key
        .and_then(|b| crate::ethereum_address_from_sec1_bytes(b.as_ref()))
        .ok_or(AttestationVerificationError::MissingRequiredField(
            "public_key",
        ))?;

    if derived_address != signer {
        return Err(AttestationVerificationError::AddressMismatch(
            signer,
            derived_address,
        ));
    }

    Ok(())
}

/// Verifies an attestation, this should be the COSESign1 attestation from the enclave.
///
/// This function will:
/// - Decode the COSESign1 structure.
/// - Validate all CA certs against the root of trust
/// - Verify the signature of the payload
/// - Return the payload as a deserialized [`AttestationDoc`].
///
/// This function is the "low-level" verification of the root of trust of the attestation.
/// For protocol level verification, see [`verify_attestation_for_signer`].
pub fn verify_attestation(attestation: &[u8]) -> AttestResult<AttestationDoc> {
    attestation_doc_validation::validate_and_parse_attestation_doc(attestation)
}

/// Run each raw attestation through Nitro CA verification, the SP1 TEE
/// version filter, and the SEC1 → Ethereum-address derivation. Attestations
/// that fail any step are silently skipped; a single `warn!` reports the
/// aggregate skip count.
///
/// This is the trust-establishing step for `/signers`: the snapshot
/// generator must run it on fresh raw attestations before publishing. The
/// stub does not call this on the read path — the snapshot artifact already
/// contains the verified set.
pub fn derive_signers(raw_attestations: &[RawAttestation], sp1_tee_version: u32) -> Vec<Address> {
    let total = raw_attestations.len();
    let signers: Vec<Address> = raw_attestations
        .iter()
        .filter_map(|raw| verify_attestation(&raw.attestation).ok())
        .filter(|doc| {
            doc.user_data
                .as_ref()
                .map(|u| u.as_slice() == sp1_tee_version.to_le_bytes())
                .unwrap_or(false)
        })
        .filter_map(|doc| crate::ethereum_address_from_sec1_bytes(doc.public_key.as_ref()?))
        .collect();
    let skipped = total.saturating_sub(signers.len());
    if skipped > 0 {
        tracing::warn!(
            "derive_signers: skipped {skipped} of {total} attestations \
             (verify failed, version mismatch, or bad pubkey)"
        );
    }
    signers
}

#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum ReadSnapshotError {
    #[error("snapshot {bucket}/{key} not found")]
    NotFound { bucket: String, key: String },

    #[error("snapshot size {size} exceeds {MAX_SNAPSHOT_BYTES} byte cap")]
    TooLarge { size: usize },

    #[error("Failed to GetObject snapshot {bucket}/{key}: {source:?}")]
    S3GetObject {
        bucket: String,
        key: String,
        source: SdkError<GetObjectError>,
    },

    #[error("Failed to read snapshot bytestream: {0}")]
    ByteStream(#[from] ByteStreamError),

    #[error("Failed to decode snapshot: {0}")]
    Decode(bincode::Error),

    #[error("Snapshot schema_version mismatch: expected {expected}, got {actual}")]
    SchemaVersionMismatch { expected: u32, actual: u32 },

    #[error("Snapshot sp1_tee_version mismatch: expected {expected}, got {actual}")]
    Sp1TeeVersionMismatch { expected: u32, actual: u32 },

    #[error("Snapshot signer list is empty")]
    EmptySigners,
}

#[derive(Debug, thiserror::Error)]
#[allow(clippy::large_enum_variant)]
pub enum WriteSnapshotError {
    #[error(
        "Refusing to write snapshot with 0 valid signers (saw {source_count} raw attestations)"
    )]
    NoValidSigners { source_count: usize },

    #[error("Failed to encode snapshot: {0}")]
    Encode(#[from] bincode::Error),

    #[error("Failed to PutObject snapshot {bucket}/{key}: {source:?}")]
    S3PutObject {
        bucket: String,
        key: String,
        source: SdkError<PutObjectError>,
    },
}

/// Decode a serialized snapshot and apply schema/version/empty validation.
///
/// Pure function so handlers and tests can validate against in-memory
/// bytes without an S3 client. Used both by the network read path
/// ([`read_signers_snapshot`]) and by tests.
#[allow(clippy::result_large_err)]
pub fn decode_and_validate_snapshot(
    bytes: &[u8],
    expected_sp1_tee_version: u32,
) -> Result<SignersSnapshot, ReadSnapshotError> {
    let snapshot: SignersSnapshot =
        bincode::deserialize(bytes).map_err(ReadSnapshotError::Decode)?;
    if snapshot.schema_version != SNAPSHOT_SCHEMA_VERSION {
        return Err(ReadSnapshotError::SchemaVersionMismatch {
            expected: SNAPSHOT_SCHEMA_VERSION,
            actual: snapshot.schema_version,
        });
    }
    if snapshot.sp1_tee_version != expected_sp1_tee_version {
        return Err(ReadSnapshotError::Sp1TeeVersionMismatch {
            expected: expected_sp1_tee_version,
            actual: snapshot.sp1_tee_version,
        });
    }
    if snapshot.signers.is_empty() {
        return Err(ReadSnapshotError::EmptySigners);
    }
    Ok(snapshot)
}

/// Read the durable `/signers` snapshot from the dedicated snapshots bucket.
///
/// Returns the decoded [`SignersSnapshot`] after validating schema_version,
/// sp1_tee_version, and a non-empty signer list. There is intentionally no
/// fallback to live derivation: missing/corrupt/wrong-version/empty all
/// surface as errors so the stub can return a clear 503.
#[allow(clippy::result_large_err)]
pub async fn read_signers_snapshot(
    bucket: &str,
    expected_sp1_tee_version: u32,
) -> Result<SignersSnapshot, ReadSnapshotError> {
    let client = s3_client_write().await;
    let key = snapshot_key(expected_sp1_tee_version);

    let object = match client.get_object().bucket(bucket).key(&key).send().await {
        Ok(o) => o,
        Err(e) => {
            if let SdkError::ServiceError(svc) = &e {
                if matches!(svc.err(), GetObjectError::NoSuchKey(_)) {
                    return Err(ReadSnapshotError::NotFound {
                        bucket: bucket.to_string(),
                        key,
                    });
                }
            }
            return Err(ReadSnapshotError::S3GetObject {
                bucket: bucket.to_string(),
                key,
                source: e,
            });
        }
    };

    if let Some(len) = object.content_length() {
        if len > MAX_SNAPSHOT_BYTES as i64 {
            return Err(ReadSnapshotError::TooLarge { size: len as usize });
        }
    }

    let bytes = object.body.collect().await?.to_vec();
    if bytes.len() > MAX_SNAPSHOT_BYTES {
        return Err(ReadSnapshotError::TooLarge { size: bytes.len() });
    }

    decode_and_validate_snapshot(&bytes, expected_sp1_tee_version)
}

/// Build a [`SignersSnapshot`] from a verified signer list, stamping the
/// current wall-clock time. The caller (`sp1-tee-snapshot-generate`) is
/// responsible for ensuring `signers` came from a fresh
/// [`derive_signers`] pass over freshly retrieved raw attestations.
pub fn build_snapshot(
    sp1_tee_version: u32,
    signers: Vec<Address>,
    source_count: usize,
) -> SignersSnapshot {
    let generated_at_unix = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    SignersSnapshot {
        schema_version: SNAPSHOT_SCHEMA_VERSION,
        sp1_tee_version,
        generated_at_unix,
        signers,
        source_count: source_count as u64,
    }
}

/// Write a fresh snapshot to S3.
///
/// Refuses to write if the snapshot's signer list is empty — defense in
/// depth against `/signers` regressing to a known-bad state. Idempotent:
/// repeated calls overwrite the same key with the latest body.
#[allow(clippy::result_large_err)]
pub async fn write_signers_snapshot(
    bucket: &str,
    snapshot: &SignersSnapshot,
) -> Result<(), WriteSnapshotError> {
    if snapshot.signers.is_empty() {
        return Err(WriteSnapshotError::NoValidSigners {
            source_count: snapshot.source_count as usize,
        });
    }
    let body = bincode::serialize(snapshot)?;
    let client = s3_client_write().await;
    let key = snapshot_key(snapshot.sp1_tee_version);
    client
        .put_object()
        .bucket(bucket)
        .key(&key)
        .body(body.into())
        .send()
        .await
        .map_err(|e| WriteSnapshotError::S3PutObject {
            bucket: bucket.to_string(),
            key,
            source: e,
        })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::address;

    fn snapshot_with(signers: Vec<Address>, version: u32) -> SignersSnapshot {
        SignersSnapshot {
            schema_version: SNAPSHOT_SCHEMA_VERSION,
            sp1_tee_version: version,
            generated_at_unix: 1_700_000_000,
            signers,
            source_count: 1,
        }
    }

    fn sample_signer() -> Address {
        address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    }

    #[test]
    fn snapshot_roundtrip_preserves_equality() {
        let original = snapshot_with(vec![sample_signer()], 1);
        let bytes = bincode::serialize(&original).unwrap();
        let restored: SignersSnapshot = bincode::deserialize(&bytes).unwrap();
        assert_eq!(original, restored);
    }

    #[test]
    fn decode_happy_path_returns_snapshot() {
        let original = snapshot_with(vec![sample_signer()], 1);
        let bytes = bincode::serialize(&original).unwrap();
        let result = decode_and_validate_snapshot(&bytes, 1).expect("valid snapshot accepted");
        assert_eq!(result, original);
    }

    #[test]
    fn decode_rejects_corrupt_bytes() {
        let result = decode_and_validate_snapshot(b"not a snapshot", 1);
        assert!(matches!(result, Err(ReadSnapshotError::Decode(_))));
    }

    #[test]
    fn decode_rejects_schema_version_mismatch() {
        let bad = SignersSnapshot {
            schema_version: SNAPSHOT_SCHEMA_VERSION + 1,
            ..snapshot_with(vec![sample_signer()], 1)
        };
        let bytes = bincode::serialize(&bad).unwrap();
        let result = decode_and_validate_snapshot(&bytes, 1);
        match result {
            Err(ReadSnapshotError::SchemaVersionMismatch { expected, actual }) => {
                assert_eq!(expected, SNAPSHOT_SCHEMA_VERSION);
                assert_eq!(actual, SNAPSHOT_SCHEMA_VERSION + 1);
            }
            other => panic!("expected SchemaVersionMismatch, got {other:?}"),
        }
    }

    #[test]
    fn decode_rejects_sp1_tee_version_mismatch() {
        let snapshot = snapshot_with(vec![sample_signer()], 7);
        let bytes = bincode::serialize(&snapshot).unwrap();
        let result = decode_and_validate_snapshot(&bytes, 1);
        match result {
            Err(ReadSnapshotError::Sp1TeeVersionMismatch { expected, actual }) => {
                assert_eq!(expected, 1);
                assert_eq!(actual, 7);
            }
            other => panic!("expected Sp1TeeVersionMismatch, got {other:?}"),
        }
    }

    #[test]
    fn decode_rejects_empty_signers() {
        let snapshot = snapshot_with(vec![], 1);
        let bytes = bincode::serialize(&snapshot).unwrap();
        let result = decode_and_validate_snapshot(&bytes, 1);
        assert!(matches!(result, Err(ReadSnapshotError::EmptySigners)));
    }

    #[test]
    fn build_snapshot_stamps_metadata() {
        let snapshot = build_snapshot(1, vec![sample_signer()], 3);
        assert_eq!(snapshot.schema_version, SNAPSHOT_SCHEMA_VERSION);
        assert_eq!(snapshot.sp1_tee_version, 1);
        assert_eq!(snapshot.signers.len(), 1);
        assert_eq!(snapshot.source_count, 3);
        // generated_at_unix should be a recent value (post-2020).
        assert!(snapshot.generated_at_unix > 1_577_836_800);
    }

    #[test]
    fn snapshot_key_format() {
        assert_eq!(snapshot_key(1), "signers-v1.bin");
        assert_eq!(snapshot_key(42), "signers-v42.bin");
    }

    #[test]
    fn derive_signers_skips_invalid_attestations() {
        // Bytes that are not a valid COSESign1 attestation get filtered.
        let bogus = vec![
            RawAttestation {
                address: sample_signer(),
                attestation: b"definitely not a Nitro attestation".to_vec(),
            },
            RawAttestation {
                address: sample_signer(),
                attestation: vec![],
            },
        ];
        let signers = derive_signers(&bogus, 1);
        assert!(signers.is_empty());
    }

    #[test]
    fn derive_signers_empty_input_returns_empty() {
        let signers = derive_signers(&[], 1);
        assert!(signers.is_empty());
    }

    #[test]
    fn wire_format_is_inner_vec_address() {
        // The /signers response body is bincode::serialize(&snapshot.signers),
        // NOT bincode::serialize(&snapshot). This guards the SDK contract:
        // SDK clients deserialize the body as `Vec<Address>` directly.
        let signers = vec![
            sample_signer(),
            address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
        ];
        let snapshot = snapshot_with(signers.clone(), 1);

        // Serializing the snapshot's signers field must produce the same
        // bytes as serializing a Vec<Address> directly. This is the
        // byte-level invariant that keeps the wire format identical to
        // the historical live-derivation response.
        let from_snapshot = bincode::serialize(&snapshot.signers).unwrap();
        let from_direct = bincode::serialize(&signers).unwrap();
        assert_eq!(from_snapshot, from_direct);

        // And the SDK can decode the bytes as Vec<Address>.
        let decoded: Vec<Address> = bincode::deserialize(&from_snapshot).unwrap();
        assert_eq!(decoded, signers);
    }
}
