[package]
name = "sp1-tee-enclave"
version.workspace = true
edition.workspace = true

[dependencies]
# Protocol deps.
k256 = "0.13.4"

# executor

# Transport deps.
vsock = { workspace = true }

[build-dependencies]
cmake = "0.1"
