[package]
name = "sp1-tee-enclave"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }

# Protocol deps.
k256 = "0.13.4"
rand_core = "0.6"
sp1-tee-common = { workspace = true }

# executor

# Transport deps.
vsock = { workspace = true }

[build-dependencies]
cmake = "0.1"
