[package]
name = "sp1-tee-common"
version.workspace = true
edition.workspace = true

[dependencies]
vsock = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }